name: CI-PRE

on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.devcontainer/**'
      - '.vscode/**'

jobs:
  build-and-test:
    name: Build, checkstyle and run tests
    runs-on: ubuntu-latest
    steps:  
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Build the Docker image
        run: make build
      - name: Run formatting and style checks
        run: make pre-commit
      - name: Run tests
        run: make test
  publish-pre:
    name: Publish to pre environment
    runs-on: ubuntu-latest
    needs: build-and-test
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GIT_COMMITTER_NAME: ${{ github.actor }}
      GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
      GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          token: ${{env.GH_TOKEN}}
      - name: Set up Git committer identity
        run: |
          git config --global user.name "${{ env.GIT_COMMITTER_NAME }}"
          git config --global user.email "${{ env.GIT_COMMITTER_EMAIL }}"  
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}     
      - name: Publish to pre environment
        run: make publish-image-pre