name: CI-PRO

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '.devcontainer/**'
      - '.vscode/**'
  
jobs:
  publish-pro:
    name: Publish to pro environment
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GIT_COMMITTER_NAME: ${{ github.actor }}
      GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
      GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          token: ${{ env.GH_TOKEN }}
      - name: Set up Git committer identity
        run: |
          git config --global user.name "${{ env.GIT_COMMITTER_NAME }}"
          git config --global user.email "${{ env.GIT_COMMITTER_EMAIL }}"           
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}  
      - name: Publish to pro environment
        run: make publish-image-pro